### ISSUE TITLE
mvn install test failure

### ISSUE THREAD

**Issue by OpenSherlock** [netplex/json-smart-v2#11]
mvn install in parent directory:
Running net.minidev.asm.ASMTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.289 sec
Running net.minidev.asm.TestNewInstance
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running net.minidev.asm.TestDateConvert
can not parse:lundi 23 janvier 2012 13 h 42 PST - DateFormat.0
java.lang.NumberFormatException: For input string: "PST"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at net.minidev.asm.ConvertDate.addHour(ConvertDate.java:264)

**Comment by UrielCh** [comment]
please give me your JVM version and your system locale.

I use to build json-smart with LANG set to "fr_FR"

**Comment by UrielCh** [comment]
no response, this issue is closed
