### ISSUE TITLE
Missing file in 2.1.0 jar from maven

### ISSUE THREAD

**Issue by OpenSherlock** [netplex/json-smart-v2#12]
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: net/minidev/asm/F
ieldFilter

Opened the jar; no /asm/ found, only /json/

**Comment by OpenSherlock** [comment]
Not found in 2.1.1 from maven either
Full trace:
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: net/minidev/asm/F
ieldFilter
        at net.minidev.json.reader.JsonWriter.<clinit>(JsonWriter.java:123)
        at net.minidev.json.JSONValue.<clinit>(JSONValue.java:537)
        at net.minidev.json.parser.JSONParserReader.parse(JSONParserReader.java:
44)

It appears to me that the maven builds do not include the assessors-smart build

**Comment by sumrise** [comment]
I hava the same problem When I used maven built the program.

    public JsonSmartJsonProvider() {
        this(-1, JSONValue.defaultReader.DEFAULT_ORDERED);
    }

java.lang.NoClassDefFoundError: Could not initialize class net.minidev.json.JSONValue

**Comment by UrielCh** [comment]
the asm artifactId had been rename to accessors-smart avoiding asm.jar conflict.
swith to Json-smart 2.2 will fix this deployment issue.
