### ISSUE TITLE
IllegalAccessError thrown when calling JSONObject.toString

### ISSUE THREAD

**Issue by benjstephenson** [netplex/json-smart-v2#48]
OS: Linux 4.19-MANJARO
Java: 1.8.0_191-b12
Scala: 2.12.6
Play: 2.6.12
Nimbus JOSE 6.2

I'm using the [Nimbus JOSE](https://connect2id.com/products/nimbus-jose-jwt) library to create, encrypt and decrypt JWTs.  When I serialise the JWT and the Nimbus library then calls `JSONObject.toString` from net.minidev.json it results in an IllegalAccessError from BeanWriterASM:

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.IllegalAccessError: java/util/stream/ReferencePipeline$3]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:320)
        at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:318)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalAccessError: java/util/stream/ReferencePipeline$3
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalAccessError: java/util/stream/ReferencePipeline$3
        at net.minidev.asm.java.util.stream.ReferencePipeline$3AccAccess.get(Unknown Source)
        at net.minidev.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:21)
        at net.minidev.json.JSONValue.writeJSONString(JSONValue.java:586)
        at net.minidev.json.reader.JsonWriter.writeJSONKV(JsonWriter.java:392)
        at net.minidev.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:145)
        at net.minidev.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:1)
        at net.minidev.json.JSONObject.writeJSON(JSONObject.java:186)
        at net.minidev.json.JSONObject.toJSONString(JSONObject.java:74)
        at net.minidev.json.JSONObject.toString(JSONObject.java:272)
        at com.nimbusds.jose.Payload.toString(Payload.java:386)
`

I had thought that this could have been related to [](https://bugs.openjdk.java.net/browse/JDK-8152410) but that is reported fixed in Java 9 and backported to 8 in build 102.  Upgrading to Java 9 doesn't resolve the issue either.  I'm totally stumped as to how to debug this so any help would be greatly appreciated.

**Comment by UrielCh** [comment]
it's looks like issue #49 

it had just been fixed.
