### ISSUE TITLE
Serialize/deserialize Instant class

### ISSUE THREAD

**Issue by maxd** [netplex/json-smart-v2#5]
Hi All,

Is it possible to serialize/deserialize `Instant` class? The following unit-test:

```
import net.minidev.json.JSONValue;
import org.junit.Assert;
import org.junit.Test;

import java.time.Instant;

public class InstantTest {

    @Test
    public void test_instant() {
        Instant instant = Instant.now();

        RegularClass regularClass = new RegularClass();
        regularClass.setInstant(instant);

        String data = JSONValue.toJSONString(regularClass);
        RegularClass result = JSONValue.parse(data, RegularClass.class);

        Assert.assertEquals(result.getInstant(), instant);
    }

    public static class RegularClass {
        private Instant instant;

        public Instant getInstant() {
            return instant;
        }

        public void setInstant(Instant instant) {
            this.instant = instant;
        }
    }

}
```

throw exception:

```
java.lang.SecurityException: Prohibited package name: java.time
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:659)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at net.minidev.asm.DynamicClassLoader.defineClass(DynamicClassLoader.java:86)
    at net.minidev.asm.BeansAccessBuilder.bulid(BeansAccessBuilder.java:313)
    at net.minidev.asm.BeansAccess.get(BeansAccess.java:111)
    at net.minidev.json.JSONValue.writeJSONString(JSONValue.java:696)
    at net.minidev.json.JSONObject.writeJSONKV(JSONObject.java:102)
    at net.minidev.json.JSONValue.writeJSONString(JSONValue.java:704)
    at net.minidev.json.JSONValue.toJSONString(JSONValue.java:746)
    at net.minidev.json.JSONValue.toJSONString(JSONValue.java:724)
    at InstantTest.test_instant(InstantTest.java:16)
```

Thanks

json-smart 2.0

**Comment by bitnoodle** [comment]
I'm using v2.3 and Instant doesn't serialize, but doesn't give error either.
json-smart:  "instant":{}
gson:  "instant":{"seconds":1539715528,"nanos":849000000}
