### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found class org.objectweb.asm.MethodVisitor, but interface was expected

### ISSUE THREAD

**Issue by tukushan** [netplex/json-smart-v2#9]
When included in a project that has a dependency on org.ow2.asm.asm-4.1

```
java.lang.IncompatibleClassChangeError: Found class org.objectweb.asm.MethodVisitor, but interface was expected
	at net.minidev.asm.BeansAccessBuilder.bulid(BeansAccessBuilder.java:118)
	at net.minidev.asm.BeansAccess.get(BeansAccess.java:111)
	at net.minidev.json.writer.BeansMapper$Bean.<init>(BeansMapper.java:45)
	at net.minidev.json.writer.JsonReader.getMapper(JsonReader.java:119)
	at net.minidev.json.JSONValue.parse(JSONValue.java:206)
	at com.jayway.jsonpath.internal.spi.mapper.JsonSmartMappingProvider.map(JsonSmartMappingProvider.java:92)
	at com.jayway.jsonpath.internal.JsonReader.convert(JsonReader.java:171)
	at com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:137)
```

**Comment by UrielCh** [comment]
ASM had been upgrade from 3.3.1 to 5.0.3
this might fix this probleme.

**Comment by UrielCh** [comment]
Json Smart 2.2 is avalable on maven central.
